// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: alignmentGuide.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlignmentGuide_GuidelineOrientation int32

const (
	AlignmentGuide_GUIDELINE_ORIENTATION_HORIZONTAL AlignmentGuide_GuidelineOrientation = 0
	AlignmentGuide_GUIDELINE_ORIENTATION_VERTICAL   AlignmentGuide_GuidelineOrientation = 1
)

// Enum value maps for AlignmentGuide_GuidelineOrientation.
var (
	AlignmentGuide_GuidelineOrientation_name = map[int32]string{
		0: "GUIDELINE_ORIENTATION_HORIZONTAL",
		1: "GUIDELINE_ORIENTATION_VERTICAL",
	}
	AlignmentGuide_GuidelineOrientation_value = map[string]int32{
		"GUIDELINE_ORIENTATION_HORIZONTAL": 0,
		"GUIDELINE_ORIENTATION_VERTICAL":   1,
	}
)

func (x AlignmentGuide_GuidelineOrientation) Enum() *AlignmentGuide_GuidelineOrientation {
	p := new(AlignmentGuide_GuidelineOrientation)
	*p = x
	return p
}

func (x AlignmentGuide_GuidelineOrientation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlignmentGuide_GuidelineOrientation) Descriptor() protoreflect.EnumDescriptor {
	return file_alignmentGuide_proto_enumTypes[0].Descriptor()
}

func (AlignmentGuide_GuidelineOrientation) Type() protoreflect.EnumType {
	return &file_alignmentGuide_proto_enumTypes[0]
}

func (x AlignmentGuide_GuidelineOrientation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlignmentGuide_GuidelineOrientation.Descriptor instead.
func (AlignmentGuide_GuidelineOrientation) EnumDescriptor() ([]byte, []int) {
	return file_alignmentGuide_proto_rawDescGZIP(), []int{0, 0}
}

type AlignmentGuide struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid        *UUID                               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Orientation AlignmentGuide_GuidelineOrientation `protobuf:"varint,2,opt,name=orientation,proto3,enum=rv.data.AlignmentGuide_GuidelineOrientation" json:"orientation,omitempty"`
	Location    float64                             `protobuf:"fixed64,3,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *AlignmentGuide) Reset() {
	*x = AlignmentGuide{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alignmentGuide_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlignmentGuide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlignmentGuide) ProtoMessage() {}

func (x *AlignmentGuide) ProtoReflect() protoreflect.Message {
	mi := &file_alignmentGuide_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlignmentGuide.ProtoReflect.Descriptor instead.
func (*AlignmentGuide) Descriptor() ([]byte, []int) {
	return file_alignmentGuide_proto_rawDescGZIP(), []int{0}
}

func (x *AlignmentGuide) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *AlignmentGuide) GetOrientation() AlignmentGuide_GuidelineOrientation {
	if x != nil {
		return x.Orientation
	}
	return AlignmentGuide_GUIDELINE_ORIENTATION_HORIZONTAL
}

func (x *AlignmentGuide) GetLocation() float64 {
	if x != nil {
		return x.Location
	}
	return 0
}

var File_alignmentGuide_proto protoreflect.FileDescriptor

var file_alignmentGuide_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x6c, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x75, 0x69, 0x64, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x1a,
	0x10, 0x62, 0x61, 0x73, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x81, 0x02, 0x0a, 0x0e, 0x41, 0x6c, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x47,
	0x75, 0x69, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x55, 0x49,
	0x44, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x4e, 0x0a, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x72,
	0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x6c, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x47, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x47, 0x75, 0x69, 0x64, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x4f,
	0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x65,
	0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x60, 0x0a, 0x14, 0x47, 0x75, 0x69, 0x64, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x20, 0x47,
	0x55, 0x49, 0x44, 0x45, 0x4c, 0x49, 0x4e, 0x45, 0x5f, 0x4f, 0x52, 0x49, 0x45, 0x4e, 0x54, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x4f, 0x4e, 0x54, 0x41, 0x4c, 0x10,
	0x00, 0x12, 0x22, 0x0a, 0x1e, 0x47, 0x55, 0x49, 0x44, 0x45, 0x4c, 0x49, 0x4e, 0x45, 0x5f, 0x4f,
	0x52, 0x49, 0x45, 0x4e, 0x54, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x56, 0x45, 0x52, 0x54, 0x49,
	0x43, 0x41, 0x4c, 0x10, 0x01, 0x42, 0x1c, 0x5a, 0x1a, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alignmentGuide_proto_rawDescOnce sync.Once
	file_alignmentGuide_proto_rawDescData = file_alignmentGuide_proto_rawDesc
)

func file_alignmentGuide_proto_rawDescGZIP() []byte {
	file_alignmentGuide_proto_rawDescOnce.Do(func() {
		file_alignmentGuide_proto_rawDescData = protoimpl.X.CompressGZIP(file_alignmentGuide_proto_rawDescData)
	})
	return file_alignmentGuide_proto_rawDescData
}

var file_alignmentGuide_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_alignmentGuide_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alignmentGuide_proto_goTypes = []interface{}{
	(AlignmentGuide_GuidelineOrientation)(0), // 0: rv.data.AlignmentGuide.GuidelineOrientation
	(*AlignmentGuide)(nil),                   // 1: rv.data.AlignmentGuide
	(*UUID)(nil),                             // 2: rv.data.UUID
}
var file_alignmentGuide_proto_depIdxs = []int32{
	2, // 0: rv.data.AlignmentGuide.uuid:type_name -> rv.data.UUID
	0, // 1: rv.data.AlignmentGuide.orientation:type_name -> rv.data.AlignmentGuide.GuidelineOrientation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_alignmentGuide_proto_init() }
func file_alignmentGuide_proto_init() {
	if File_alignmentGuide_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_alignmentGuide_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlignmentGuide); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alignmentGuide_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alignmentGuide_proto_goTypes,
		DependencyIndexes: file_alignmentGuide_proto_depIdxs,
		EnumInfos:         file_alignmentGuide_proto_enumTypes,
		MessageInfos:      file_alignmentGuide_proto_msgTypes,
	}.Build()
	File_alignmentGuide_proto = out.File
	file_alignmentGuide_proto_rawDesc = nil
	file_alignmentGuide_proto_goTypes = nil
	file_alignmentGuide_proto_depIdxs = nil
}
