// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: effects.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Effect_EffectVariable_EffectDirection_EffectDirection int32

const (
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_NONE         Effect_EffectVariable_EffectDirection_EffectDirection = 0
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_TOP_LEFT     Effect_EffectVariable_EffectDirection_EffectDirection = 1
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_TOP          Effect_EffectVariable_EffectDirection_EffectDirection = 2
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_TOP_RIGHT    Effect_EffectVariable_EffectDirection_EffectDirection = 4
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_LEFT         Effect_EffectVariable_EffectDirection_EffectDirection = 8
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_CENTER       Effect_EffectVariable_EffectDirection_EffectDirection = 16
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_RIGHT        Effect_EffectVariable_EffectDirection_EffectDirection = 32
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_BOTTOM_LEFT  Effect_EffectVariable_EffectDirection_EffectDirection = 64
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_BOTTOM       Effect_EffectVariable_EffectDirection_EffectDirection = 128
	Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_BOTTOM_RIGHT Effect_EffectVariable_EffectDirection_EffectDirection = 256
)

// Enum value maps for Effect_EffectVariable_EffectDirection_EffectDirection.
var (
	Effect_EffectVariable_EffectDirection_EffectDirection_name = map[int32]string{
		0:   "EFFECT_DIRECTION_NONE",
		1:   "EFFECT_DIRECTION_TOP_LEFT",
		2:   "EFFECT_DIRECTION_TOP",
		4:   "EFFECT_DIRECTION_TOP_RIGHT",
		8:   "EFFECT_DIRECTION_LEFT",
		16:  "EFFECT_DIRECTION_CENTER",
		32:  "EFFECT_DIRECTION_RIGHT",
		64:  "EFFECT_DIRECTION_BOTTOM_LEFT",
		128: "EFFECT_DIRECTION_BOTTOM",
		256: "EFFECT_DIRECTION_BOTTOM_RIGHT",
	}
	Effect_EffectVariable_EffectDirection_EffectDirection_value = map[string]int32{
		"EFFECT_DIRECTION_NONE":         0,
		"EFFECT_DIRECTION_TOP_LEFT":     1,
		"EFFECT_DIRECTION_TOP":          2,
		"EFFECT_DIRECTION_TOP_RIGHT":    4,
		"EFFECT_DIRECTION_LEFT":         8,
		"EFFECT_DIRECTION_CENTER":       16,
		"EFFECT_DIRECTION_RIGHT":        32,
		"EFFECT_DIRECTION_BOTTOM_LEFT":  64,
		"EFFECT_DIRECTION_BOTTOM":       128,
		"EFFECT_DIRECTION_BOTTOM_RIGHT": 256,
	}
)

func (x Effect_EffectVariable_EffectDirection_EffectDirection) Enum() *Effect_EffectVariable_EffectDirection_EffectDirection {
	p := new(Effect_EffectVariable_EffectDirection_EffectDirection)
	*p = x
	return p
}

func (x Effect_EffectVariable_EffectDirection_EffectDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Effect_EffectVariable_EffectDirection_EffectDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_effects_proto_enumTypes[0].Descriptor()
}

func (Effect_EffectVariable_EffectDirection_EffectDirection) Type() protoreflect.EnumType {
	return &file_effects_proto_enumTypes[0]
}

func (x Effect_EffectVariable_EffectDirection_EffectDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Effect_EffectVariable_EffectDirection_EffectDirection.Descriptor instead.
func (Effect_EffectVariable_EffectDirection_EffectDirection) EnumDescriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 0, 4, 0}
}

type Effect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid                *UUID                    `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Enabled             bool                     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Name                string                   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	RenderId            string                   `protobuf:"bytes,4,opt,name=render_id,json=renderId,proto3" json:"render_id,omitempty"`
	BehaviorDescription string                   `protobuf:"bytes,5,opt,name=behavior_description,json=behaviorDescription,proto3" json:"behavior_description,omitempty"`
	Category            string                   `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Variables           []*Effect_EffectVariable `protobuf:"bytes,7,rep,name=variables,proto3" json:"variables,omitempty"`
}

func (x *Effect) Reset() {
	*x = Effect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_effects_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect.ProtoReflect.Descriptor instead.
func (*Effect) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0}
}

func (x *Effect) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Effect) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Effect) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Effect) GetRenderId() string {
	if x != nil {
		return x.RenderId
	}
	return ""
}

func (x *Effect) GetBehaviorDescription() string {
	if x != nil {
		return x.BehaviorDescription
	}
	return ""
}

func (x *Effect) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Effect) GetVariables() []*Effect_EffectVariable {
	if x != nil {
		return x.Variables
	}
	return nil
}

type Transition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration     float64 `protobuf:"fixed64,1,opt,name=duration,proto3" json:"duration,omitempty"`
	FavoriteUuid *UUID   `protobuf:"bytes,2,opt,name=favorite_uuid,json=favoriteUuid,proto3" json:"favorite_uuid,omitempty"`
	Effect       *Effect `protobuf:"bytes,3,opt,name=effect,proto3" json:"effect,omitempty"`
}

func (x *Transition) Reset() {
	*x = Transition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_effects_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transition) ProtoMessage() {}

func (x *Transition) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transition.ProtoReflect.Descriptor instead.
func (*Transition) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{1}
}

func (x *Transition) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Transition) GetFavoriteUuid() *UUID {
	if x != nil {
		return x.FavoriteUuid
	}
	return nil
}

func (x *Transition) GetEffect() *Effect {
	if x != nil {
		return x.Effect
	}
	return nil
}

type Effect_EffectVariable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are assignable to Type:
	//	*Effect_EffectVariable_Int
	//	*Effect_EffectVariable_Float
	//	*Effect_EffectVariable_Color
	//	*Effect_EffectVariable_Direction
	//	*Effect_EffectVariable_Double
	Type isEffect_EffectVariable_Type `protobuf_oneof:"Type"`
}

func (x *Effect_EffectVariable) Reset() {
	*x = Effect_EffectVariable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_effects_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Effect_EffectVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_EffectVariable) ProtoMessage() {}

func (x *Effect_EffectVariable) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect_EffectVariable.ProtoReflect.Descriptor instead.
func (*Effect_EffectVariable) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Effect_EffectVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Effect_EffectVariable) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (m *Effect_EffectVariable) GetType() isEffect_EffectVariable_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Effect_EffectVariable) GetInt() *Effect_EffectVariable_EffectInt {
	if x, ok := x.GetType().(*Effect_EffectVariable_Int); ok {
		return x.Int
	}
	return nil
}

func (x *Effect_EffectVariable) GetFloat() *Effect_EffectVariable_EffectFloat {
	if x, ok := x.GetType().(*Effect_EffectVariable_Float); ok {
		return x.Float
	}
	return nil
}

func (x *Effect_EffectVariable) GetColor() *Effect_EffectVariable_EffectColor {
	if x, ok := x.GetType().(*Effect_EffectVariable_Color); ok {
		return x.Color
	}
	return nil
}

func (x *Effect_EffectVariable) GetDirection() *Effect_EffectVariable_EffectDirection {
	if x, ok := x.GetType().(*Effect_EffectVariable_Direction); ok {
		return x.Direction
	}
	return nil
}

func (x *Effect_EffectVariable) GetDouble() *Effect_EffectVariable_EffectDouble {
	if x, ok := x.GetType().(*Effect_EffectVariable_Double); ok {
		return x.Double
	}
	return nil
}

type isEffect_EffectVariable_Type interface {
	isEffect_EffectVariable_Type()
}

type Effect_EffectVariable_Int struct {
	Int *Effect_EffectVariable_EffectInt `protobuf:"bytes,3,opt,name=int,proto3,oneof"`
}

type Effect_EffectVariable_Float struct {
	Float *Effect_EffectVariable_EffectFloat `protobuf:"bytes,4,opt,name=float,proto3,oneof"`
}

type Effect_EffectVariable_Color struct {
	Color *Effect_EffectVariable_EffectColor `protobuf:"bytes,5,opt,name=color,proto3,oneof"`
}

type Effect_EffectVariable_Direction struct {
	Direction *Effect_EffectVariable_EffectDirection `protobuf:"bytes,6,opt,name=direction,proto3,oneof"`
}

type Effect_EffectVariable_Double struct {
	Double *Effect_EffectVariable_EffectDouble `protobuf:"bytes,7,opt,name=double,proto3,oneof"`
}

func (*Effect_EffectVariable_Int) isEffect_EffectVariable_Type() {}

func (*Effect_EffectVariable_Float) isEffect_EffectVariable_Type() {}

func (*Effect_EffectVariable_Color) isEffect_EffectVariable_Type() {}

func (*Effect_EffectVariable_Direction) isEffect_EffectVariable_Type() {}

func (*Effect_EffectVariable_Double) isEffect_EffectVariable_Type() {}

type Effect_Preset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    *UUID     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name    string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Effects []*Effect `protobuf:"bytes,3,rep,name=effects,proto3" json:"effects,omitempty"`
}

func (x *Effect_Preset) Reset() {
	*x = Effect_Preset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_effects_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Effect_Preset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_Preset) ProtoMessage() {}

func (x *Effect_Preset) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect_Preset.ProtoReflect.Descriptor instead.
func (*Effect_Preset) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Effect_Preset) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Effect_Preset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Effect_Preset) GetEffects() []*Effect {
	if x != nil {
		return x.Effects
	}
	return nil
}

type Effect_EffectVariable_EffectInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value        int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	DefaultValue int32 `protobuf:"varint,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Min          int32 `protobuf:"varint,3,opt,name=min,proto3" json:"min,omitempty"`
	Max          int32 `protobuf:"varint,4,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *Effect_EffectVariable_EffectInt) Reset() {
	*x = Effect_EffectVariable_EffectInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_effects_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Effect_EffectVariable_EffectInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_EffectVariable_EffectInt) ProtoMessage() {}

func (x *Effect_EffectVariable_EffectInt) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect_EffectVariable_EffectInt.ProtoReflect.Descriptor instead.
func (*Effect_EffectVariable_EffectInt) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Effect_EffectVariable_EffectInt) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Effect_EffectVariable_EffectInt) GetDefaultValue() int32 {
	if x != nil {
		return x.DefaultValue
	}
	return 0
}

func (x *Effect_EffectVariable_EffectInt) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Effect_EffectVariable_EffectInt) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Effect_EffectVariable_EffectFloat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value        float32 `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	DefaultValue float32 `protobuf:"fixed32,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Min          float32 `protobuf:"fixed32,3,opt,name=min,proto3" json:"min,omitempty"`
	Max          float32 `protobuf:"fixed32,4,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *Effect_EffectVariable_EffectFloat) Reset() {
	*x = Effect_EffectVariable_EffectFloat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_effects_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Effect_EffectVariable_EffectFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_EffectVariable_EffectFloat) ProtoMessage() {}

func (x *Effect_EffectVariable_EffectFloat) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect_EffectVariable_EffectFloat.ProtoReflect.Descriptor instead.
func (*Effect_EffectVariable_EffectFloat) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Effect_EffectVariable_EffectFloat) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Effect_EffectVariable_EffectFloat) GetDefaultValue() float32 {
	if x != nil {
		return x.DefaultValue
	}
	return 0
}

func (x *Effect_EffectVariable_EffectFloat) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Effect_EffectVariable_EffectFloat) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Effect_EffectVariable_EffectDouble struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value        float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	DefaultValue float64 `protobuf:"fixed64,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Min          float64 `protobuf:"fixed64,3,opt,name=min,proto3" json:"min,omitempty"`
	Max          float64 `protobuf:"fixed64,4,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *Effect_EffectVariable_EffectDouble) Reset() {
	*x = Effect_EffectVariable_EffectDouble{}
	if protoimpl.UnsafeEnabled {
		mi := &file_effects_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Effect_EffectVariable_EffectDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_EffectVariable_EffectDouble) ProtoMessage() {}

func (x *Effect_EffectVariable_EffectDouble) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect_EffectVariable_EffectDouble.ProtoReflect.Descriptor instead.
func (*Effect_EffectVariable_EffectDouble) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *Effect_EffectVariable_EffectDouble) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Effect_EffectVariable_EffectDouble) GetDefaultValue() float64 {
	if x != nil {
		return x.DefaultValue
	}
	return 0
}

func (x *Effect_EffectVariable_EffectDouble) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Effect_EffectVariable_EffectDouble) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Effect_EffectVariable_EffectColor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color        *Color `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	DefaultColor *Color `protobuf:"bytes,2,opt,name=default_color,json=defaultColor,proto3" json:"default_color,omitempty"`
}

func (x *Effect_EffectVariable_EffectColor) Reset() {
	*x = Effect_EffectVariable_EffectColor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_effects_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Effect_EffectVariable_EffectColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_EffectVariable_EffectColor) ProtoMessage() {}

func (x *Effect_EffectVariable_EffectColor) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect_EffectVariable_EffectColor.ProtoReflect.Descriptor instead.
func (*Effect_EffectVariable_EffectColor) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 0, 3}
}

func (x *Effect_EffectVariable_EffectColor) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Effect_EffectVariable_EffectColor) GetDefaultColor() *Color {
	if x != nil {
		return x.DefaultColor
	}
	return nil
}

type Effect_EffectVariable_EffectDirection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direction           Effect_EffectVariable_EffectDirection_EffectDirection `protobuf:"varint,1,opt,name=direction,proto3,enum=rv.data.Effect_EffectVariable_EffectDirection_EffectDirection" json:"direction,omitempty"`
	DefaultDirection    Effect_EffectVariable_EffectDirection_EffectDirection `protobuf:"varint,2,opt,name=default_direction,json=defaultDirection,proto3,enum=rv.data.Effect_EffectVariable_EffectDirection_EffectDirection" json:"default_direction,omitempty"`
	AvailableDirections uint32                                                `protobuf:"varint,3,opt,name=available_directions,json=availableDirections,proto3" json:"available_directions,omitempty"`
}

func (x *Effect_EffectVariable_EffectDirection) Reset() {
	*x = Effect_EffectVariable_EffectDirection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_effects_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Effect_EffectVariable_EffectDirection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect_EffectVariable_EffectDirection) ProtoMessage() {}

func (x *Effect_EffectVariable_EffectDirection) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect_EffectVariable_EffectDirection.ProtoReflect.Descriptor instead.
func (*Effect_EffectVariable_EffectDirection) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{0, 0, 4}
}

func (x *Effect_EffectVariable_EffectDirection) GetDirection() Effect_EffectVariable_EffectDirection_EffectDirection {
	if x != nil {
		return x.Direction
	}
	return Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_NONE
}

func (x *Effect_EffectVariable_EffectDirection) GetDefaultDirection() Effect_EffectVariable_EffectDirection_EffectDirection {
	if x != nil {
		return x.DefaultDirection
	}
	return Effect_EffectVariable_EffectDirection_EFFECT_DIRECTION_NONE
}

func (x *Effect_EffectVariable_EffectDirection) GetAvailableDirections() uint32 {
	if x != nil {
		return x.AvailableDirections
	}
	return 0
}

type Transition_Preset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid       *UUID       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name       string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Transition *Transition `protobuf:"bytes,3,opt,name=transition,proto3" json:"transition,omitempty"`
}

func (x *Transition_Preset) Reset() {
	*x = Transition_Preset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_effects_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transition_Preset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transition_Preset) ProtoMessage() {}

func (x *Transition_Preset) ProtoReflect() protoreflect.Message {
	mi := &file_effects_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transition_Preset.ProtoReflect.Descriptor instead.
func (*Transition_Preset) Descriptor() ([]byte, []int) {
	return file_effects_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Transition_Preset) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Transition_Preset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Transition_Preset) GetTransition() *Transition {
	if x != nil {
		return x.Transition
	}
	return nil
}

var File_effects_proto protoreflect.FileDescriptor

var file_effects_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x10, 0x62, 0x61, 0x73, 0x69, 0x63, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x0e, 0x0a, 0x06, 0x45,
	0x66, 0x66, 0x65, 0x63, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x55,
	0x49, 0x44, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x14, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x5f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x13, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x3c, 0x0a, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73,
	0x1a, 0xb0, 0x0b, 0x0a, 0x0e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x03, 0x69, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x42, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x48, 0x00, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x42, 0x0a, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x72, 0x76, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x2e, 0x45, 0x66, 0x66, 0x65,
	0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12,
	0x4e, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x66, 0x66,
	0x65, 0x63, 0x74, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x00, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x45, 0x0a, 0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74,
	0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x2e,
	0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x06,
	0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x1a, 0x6a, 0x0a, 0x09, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74,
	0x49, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x69, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d,
	0x61, 0x78, 0x1a, 0x6c, 0x0a, 0x0b, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x46, 0x6c, 0x6f, 0x61,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6d, 0x61, 0x78,
	0x1a, 0x6d, 0x0a, 0x0c, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x1a,
	0x68, 0x0a, 0x0b, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x24,
	0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x33, 0x0a, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x76,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x0c, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x1a, 0xcf, 0x04, 0x0a, 0x0f, 0x45, 0x66,
	0x66, 0x65, 0x63, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x5c, 0x0a,
	0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x3e, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x6b, 0x0a, 0x11, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3e, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x14, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xbd, 0x02, 0x0a, 0x0f,
	0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x19, 0x0a, 0x15, 0x45, 0x46, 0x46, 0x45, 0x43, 0x54, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x45, 0x46,
	0x46, 0x45, 0x43, 0x54, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54,
	0x4f, 0x50, 0x5f, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x46, 0x46,
	0x45, 0x43, 0x54, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x4f,
	0x50, 0x10, 0x02, 0x12, 0x1e, 0x0a, 0x1a, 0x45, 0x46, 0x46, 0x45, 0x43, 0x54, 0x5f, 0x44, 0x49,
	0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x4f, 0x50, 0x5f, 0x52, 0x49, 0x47, 0x48,
	0x54, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x46, 0x46, 0x45, 0x43, 0x54, 0x5f, 0x44, 0x49,
	0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x08, 0x12, 0x1b,
	0x0a, 0x17, 0x45, 0x46, 0x46, 0x45, 0x43, 0x54, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x43, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x10, 0x10, 0x12, 0x1a, 0x0a, 0x16, 0x45,
	0x46, 0x46, 0x45, 0x43, 0x54, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x52, 0x49, 0x47, 0x48, 0x54, 0x10, 0x20, 0x12, 0x20, 0x0a, 0x1c, 0x45, 0x46, 0x46, 0x45, 0x43,
	0x54, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x42, 0x4f, 0x54, 0x54,
	0x4f, 0x4d, 0x5f, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x40, 0x12, 0x1c, 0x0a, 0x17, 0x45, 0x46, 0x46,
	0x45, 0x43, 0x54, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x42, 0x4f,
	0x54, 0x54, 0x4f, 0x4d, 0x10, 0x80, 0x01, 0x12, 0x22, 0x0a, 0x1d, 0x45, 0x46, 0x46, 0x45, 0x43,
	0x54, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x42, 0x4f, 0x54, 0x54,
	0x4f, 0x4d, 0x5f, 0x52, 0x49, 0x47, 0x48, 0x54, 0x10, 0x80, 0x02, 0x42, 0x06, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x1a, 0x6a, 0x0a, 0x06, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x12, 0x21, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x76,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x52, 0x07, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x73, 0x22,
	0xfb, 0x01, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x0d, 0x66, 0x61,
	0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x55, 0x49, 0x44,
	0x52, 0x0c, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x55, 0x75, 0x69, 0x64, 0x12, 0x27,
	0x0a, 0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x52,
	0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x1a, 0x74, 0x0a, 0x06, 0x50, 0x72, 0x65, 0x73, 0x65,
	0x74, 0x12, 0x21, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72,
	0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x1c, 0x5a,
	0x1a, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x65, 0x6e, 0x63,
	0x6f, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_effects_proto_rawDescOnce sync.Once
	file_effects_proto_rawDescData = file_effects_proto_rawDesc
)

func file_effects_proto_rawDescGZIP() []byte {
	file_effects_proto_rawDescOnce.Do(func() {
		file_effects_proto_rawDescData = protoimpl.X.CompressGZIP(file_effects_proto_rawDescData)
	})
	return file_effects_proto_rawDescData
}

var file_effects_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_effects_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_effects_proto_goTypes = []interface{}{
	(Effect_EffectVariable_EffectDirection_EffectDirection)(0), // 0: rv.data.Effect.EffectVariable.EffectDirection.EffectDirection
	(*Effect)(nil),                                // 1: rv.data.Effect
	(*Transition)(nil),                            // 2: rv.data.Transition
	(*Effect_EffectVariable)(nil),                 // 3: rv.data.Effect.EffectVariable
	(*Effect_Preset)(nil),                         // 4: rv.data.Effect.Preset
	(*Effect_EffectVariable_EffectInt)(nil),       // 5: rv.data.Effect.EffectVariable.EffectInt
	(*Effect_EffectVariable_EffectFloat)(nil),     // 6: rv.data.Effect.EffectVariable.EffectFloat
	(*Effect_EffectVariable_EffectDouble)(nil),    // 7: rv.data.Effect.EffectVariable.EffectDouble
	(*Effect_EffectVariable_EffectColor)(nil),     // 8: rv.data.Effect.EffectVariable.EffectColor
	(*Effect_EffectVariable_EffectDirection)(nil), // 9: rv.data.Effect.EffectVariable.EffectDirection
	(*Transition_Preset)(nil),                     // 10: rv.data.Transition.Preset
	(*UUID)(nil),                                  // 11: rv.data.UUID
	(*Color)(nil),                                 // 12: rv.data.Color
}
var file_effects_proto_depIdxs = []int32{
	11, // 0: rv.data.Effect.uuid:type_name -> rv.data.UUID
	3,  // 1: rv.data.Effect.variables:type_name -> rv.data.Effect.EffectVariable
	11, // 2: rv.data.Transition.favorite_uuid:type_name -> rv.data.UUID
	1,  // 3: rv.data.Transition.effect:type_name -> rv.data.Effect
	5,  // 4: rv.data.Effect.EffectVariable.int:type_name -> rv.data.Effect.EffectVariable.EffectInt
	6,  // 5: rv.data.Effect.EffectVariable.float:type_name -> rv.data.Effect.EffectVariable.EffectFloat
	8,  // 6: rv.data.Effect.EffectVariable.color:type_name -> rv.data.Effect.EffectVariable.EffectColor
	9,  // 7: rv.data.Effect.EffectVariable.direction:type_name -> rv.data.Effect.EffectVariable.EffectDirection
	7,  // 8: rv.data.Effect.EffectVariable.double:type_name -> rv.data.Effect.EffectVariable.EffectDouble
	11, // 9: rv.data.Effect.Preset.uuid:type_name -> rv.data.UUID
	1,  // 10: rv.data.Effect.Preset.effects:type_name -> rv.data.Effect
	12, // 11: rv.data.Effect.EffectVariable.EffectColor.color:type_name -> rv.data.Color
	12, // 12: rv.data.Effect.EffectVariable.EffectColor.default_color:type_name -> rv.data.Color
	0,  // 13: rv.data.Effect.EffectVariable.EffectDirection.direction:type_name -> rv.data.Effect.EffectVariable.EffectDirection.EffectDirection
	0,  // 14: rv.data.Effect.EffectVariable.EffectDirection.default_direction:type_name -> rv.data.Effect.EffectVariable.EffectDirection.EffectDirection
	11, // 15: rv.data.Transition.Preset.uuid:type_name -> rv.data.UUID
	2,  // 16: rv.data.Transition.Preset.transition:type_name -> rv.data.Transition
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_effects_proto_init() }
func file_effects_proto_init() {
	if File_effects_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_effects_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Effect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_effects_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_effects_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Effect_EffectVariable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_effects_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Effect_Preset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_effects_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Effect_EffectVariable_EffectInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_effects_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Effect_EffectVariable_EffectFloat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_effects_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Effect_EffectVariable_EffectDouble); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_effects_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Effect_EffectVariable_EffectColor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_effects_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Effect_EffectVariable_EffectDirection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_effects_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transition_Preset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_effects_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Effect_EffectVariable_Int)(nil),
		(*Effect_EffectVariable_Float)(nil),
		(*Effect_EffectVariable_Color)(nil),
		(*Effect_EffectVariable_Direction)(nil),
		(*Effect_EffectVariable_Double)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_effects_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_effects_proto_goTypes,
		DependencyIndexes: file_effects_proto_depIdxs,
		EnumInfos:         file_effects_proto_enumTypes,
		MessageInfos:      file_effects_proto_msgTypes,
	}.Build()
	File_effects_proto = out.File
	file_effects_proto_rawDesc = nil
	file_effects_proto_goTypes = nil
	file_effects_proto_depIdxs = nil
}
