// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: labels.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProLabelsDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Labels []*Action_Label `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *ProLabelsDocument) Reset() {
	*x = ProLabelsDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_labels_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProLabelsDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProLabelsDocument) ProtoMessage() {}

func (x *ProLabelsDocument) ProtoReflect() protoreflect.Message {
	mi := &file_labels_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProLabelsDocument.ProtoReflect.Descriptor instead.
func (*ProLabelsDocument) Descriptor() ([]byte, []int) {
	return file_labels_proto_rawDescGZIP(), []int{0}
}

func (x *ProLabelsDocument) GetLabels() []*Action_Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_labels_proto protoreflect.FileDescriptor

var file_labels_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x73, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x06, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x76, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x42, 0x1c, 0x5a, 0x1a, 0x63, 0x6f, 0x6e,
	0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_labels_proto_rawDescOnce sync.Once
	file_labels_proto_rawDescData = file_labels_proto_rawDesc
)

func file_labels_proto_rawDescGZIP() []byte {
	file_labels_proto_rawDescOnce.Do(func() {
		file_labels_proto_rawDescData = protoimpl.X.CompressGZIP(file_labels_proto_rawDescData)
	})
	return file_labels_proto_rawDescData
}

var file_labels_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_labels_proto_goTypes = []interface{}{
	(*ProLabelsDocument)(nil), // 0: rv.data.ProLabelsDocument
	(*Action_Label)(nil),      // 1: rv.data.Action.Label
}
var file_labels_proto_depIdxs = []int32{
	1, // 0: rv.data.ProLabelsDocument.labels:type_name -> rv.data.Action.Label
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_labels_proto_init() }
func file_labels_proto_init() {
	if File_labels_proto != nil {
		return
	}
	file_action_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_labels_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProLabelsDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_labels_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_labels_proto_goTypes,
		DependencyIndexes: file_labels_proto_depIdxs,
		MessageInfos:      file_labels_proto_msgTypes,
	}.Build()
	File_labels_proto = out.File
	file_labels_proto_rawDesc = nil
	file_labels_proto_goTypes = nil
	file_labels_proto_depIdxs = nil
}
