// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: liveVideoPlaylist.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LiveVideoPlaylist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actions            []*Action `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	TargetedLayer_UUID *UUID     `protobuf:"bytes,2,opt,name=targeted_layer_UUID,json=targetedLayerUUID,proto3" json:"targeted_layer_UUID,omitempty"`
	Uuid               *UUID     `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *LiveVideoPlaylist) Reset() {
	*x = LiveVideoPlaylist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_liveVideoPlaylist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveVideoPlaylist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveVideoPlaylist) ProtoMessage() {}

func (x *LiveVideoPlaylist) ProtoReflect() protoreflect.Message {
	mi := &file_liveVideoPlaylist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveVideoPlaylist.ProtoReflect.Descriptor instead.
func (*LiveVideoPlaylist) Descriptor() ([]byte, []int) {
	return file_liveVideoPlaylist_proto_rawDescGZIP(), []int{0}
}

func (x *LiveVideoPlaylist) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *LiveVideoPlaylist) GetTargetedLayer_UUID() *UUID {
	if x != nil {
		return x.TargetedLayer_UUID
	}
	return nil
}

func (x *LiveVideoPlaylist) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

var File_liveVideoPlaylist_proto protoreflect.FileDescriptor

var file_liveVideoPlaylist_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6c, 0x69, 0x76, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x50, 0x6c, 0x61, 0x79, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x76, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x1a, 0x10, 0x62, 0x61, 0x73, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xa0, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x76, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x50, 0x6c, 0x61, 0x79, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x76, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x3d, 0x0a, 0x13, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x65, 0x64, 0x5f,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x55, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52,
	0x11, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x65, 0x64, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x55,
	0x49, 0x44, 0x12, 0x21, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x42, 0x1c, 0x5a, 0x1a, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_liveVideoPlaylist_proto_rawDescOnce sync.Once
	file_liveVideoPlaylist_proto_rawDescData = file_liveVideoPlaylist_proto_rawDesc
)

func file_liveVideoPlaylist_proto_rawDescGZIP() []byte {
	file_liveVideoPlaylist_proto_rawDescOnce.Do(func() {
		file_liveVideoPlaylist_proto_rawDescData = protoimpl.X.CompressGZIP(file_liveVideoPlaylist_proto_rawDescData)
	})
	return file_liveVideoPlaylist_proto_rawDescData
}

var file_liveVideoPlaylist_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_liveVideoPlaylist_proto_goTypes = []interface{}{
	(*LiveVideoPlaylist)(nil), // 0: rv.data.LiveVideoPlaylist
	(*Action)(nil),            // 1: rv.data.Action
	(*UUID)(nil),              // 2: rv.data.UUID
}
var file_liveVideoPlaylist_proto_depIdxs = []int32{
	1, // 0: rv.data.LiveVideoPlaylist.actions:type_name -> rv.data.Action
	2, // 1: rv.data.LiveVideoPlaylist.targeted_layer_UUID:type_name -> rv.data.UUID
	2, // 2: rv.data.LiveVideoPlaylist.uuid:type_name -> rv.data.UUID
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_liveVideoPlaylist_proto_init() }
func file_liveVideoPlaylist_proto_init() {
	if File_liveVideoPlaylist_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	file_action_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_liveVideoPlaylist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveVideoPlaylist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_liveVideoPlaylist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_liveVideoPlaylist_proto_goTypes,
		DependencyIndexes: file_liveVideoPlaylist_proto_depIdxs,
		MessageInfos:      file_liveVideoPlaylist_proto_msgTypes,
	}.Build()
	File_liveVideoPlaylist_proto = out.File
	file_liveVideoPlaylist_proto_rawDesc = nil
	file_liveVideoPlaylist_proto_goTypes = nil
	file_liveVideoPlaylist_proto_depIdxs = nil
}
