// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: macros.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MacrosDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationInfo *ApplicationInfo        `protobuf:"bytes,1,opt,name=application_info,json=applicationInfo,proto3" json:"application_info,omitempty"`
	Macros          []*MacrosDocument_Macro `protobuf:"bytes,2,rep,name=macros,proto3" json:"macros,omitempty"`
}

func (x *MacrosDocument) Reset() {
	*x = MacrosDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_macros_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MacrosDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MacrosDocument) ProtoMessage() {}

func (x *MacrosDocument) ProtoReflect() protoreflect.Message {
	mi := &file_macros_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MacrosDocument.ProtoReflect.Descriptor instead.
func (*MacrosDocument) Descriptor() ([]byte, []int) {
	return file_macros_proto_rawDescGZIP(), []int{0}
}

func (x *MacrosDocument) GetApplicationInfo() *ApplicationInfo {
	if x != nil {
		return x.ApplicationInfo
	}
	return nil
}

func (x *MacrosDocument) GetMacros() []*MacrosDocument_Macro {
	if x != nil {
		return x.Macros
	}
	return nil
}

type MacrosDocument_Macro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid             *UUID     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name             string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color            *Color    `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Actions          []*Action `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	TriggerOnStartup bool      `protobuf:"varint,5,opt,name=trigger_on_startup,json=triggerOnStartup,proto3" json:"trigger_on_startup,omitempty"`
}

func (x *MacrosDocument_Macro) Reset() {
	*x = MacrosDocument_Macro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_macros_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MacrosDocument_Macro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MacrosDocument_Macro) ProtoMessage() {}

func (x *MacrosDocument_Macro) ProtoReflect() protoreflect.Message {
	mi := &file_macros_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MacrosDocument_Macro.ProtoReflect.Descriptor instead.
func (*MacrosDocument_Macro) Descriptor() ([]byte, []int) {
	return file_macros_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MacrosDocument_Macro) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *MacrosDocument_Macro) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MacrosDocument_Macro) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *MacrosDocument_Macro) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *MacrosDocument_Macro) GetTriggerOnStartup() bool {
	if x != nil {
		return x.TriggerOnStartup
	}
	return false
}

var File_macros_proto protoreflect.FileDescriptor

var file_macros_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x61, 0x63, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x10, 0x62, 0x61, 0x73, 0x69, 0x63, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcc, 0x02, 0x0a, 0x0e, 0x4d, 0x61, 0x63, 0x72,
	0x6f, 0x73, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x43, 0x0a, 0x10, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x41,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x35, 0x0a, 0x06, 0x6d, 0x61, 0x63, 0x72, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4d, 0x61, 0x63, 0x72, 0x6f, 0x73,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x61, 0x63, 0x72, 0x6f, 0x52, 0x06,
	0x6d, 0x61, 0x63, 0x72, 0x6f, 0x73, 0x1a, 0xbd, 0x01, 0x0a, 0x05, 0x4d, 0x61, 0x63, 0x72, 0x6f,
	0x12, 0x21, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x29, 0x0a,
	0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x74, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x5f, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x4f, 0x6e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x42, 0x1c, 0x5a, 0x1a, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_macros_proto_rawDescOnce sync.Once
	file_macros_proto_rawDescData = file_macros_proto_rawDesc
)

func file_macros_proto_rawDescGZIP() []byte {
	file_macros_proto_rawDescOnce.Do(func() {
		file_macros_proto_rawDescData = protoimpl.X.CompressGZIP(file_macros_proto_rawDescData)
	})
	return file_macros_proto_rawDescData
}

var file_macros_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_macros_proto_goTypes = []interface{}{
	(*MacrosDocument)(nil),       // 0: rv.data.MacrosDocument
	(*MacrosDocument_Macro)(nil), // 1: rv.data.MacrosDocument.Macro
	(*ApplicationInfo)(nil),      // 2: rv.data.ApplicationInfo
	(*UUID)(nil),                 // 3: rv.data.UUID
	(*Color)(nil),                // 4: rv.data.Color
	(*Action)(nil),               // 5: rv.data.Action
}
var file_macros_proto_depIdxs = []int32{
	2, // 0: rv.data.MacrosDocument.application_info:type_name -> rv.data.ApplicationInfo
	1, // 1: rv.data.MacrosDocument.macros:type_name -> rv.data.MacrosDocument.Macro
	3, // 2: rv.data.MacrosDocument.Macro.uuid:type_name -> rv.data.UUID
	4, // 3: rv.data.MacrosDocument.Macro.color:type_name -> rv.data.Color
	5, // 4: rv.data.MacrosDocument.Macro.actions:type_name -> rv.data.Action
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_macros_proto_init() }
func file_macros_proto_init() {
	if File_macros_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	file_action_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_macros_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MacrosDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_macros_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MacrosDocument_Macro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_macros_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_macros_proto_goTypes,
		DependencyIndexes: file_macros_proto_depIdxs,
		MessageInfos:      file_macros_proto_msgTypes,
	}.Build()
	File_macros_proto = out.File
	file_macros_proto_rawDesc = nil
	file_macros_proto_goTypes = nil
	file_macros_proto_depIdxs = nil
}
