// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: propDocument.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationInfo *ApplicationInfo `protobuf:"bytes,1,opt,name=application_info,json=applicationInfo,proto3" json:"application_info,omitempty"`
	Cues            []*Cue           `protobuf:"bytes,2,rep,name=cues,proto3" json:"cues,omitempty"`
	Transition      *Transition      `protobuf:"bytes,3,opt,name=transition,proto3" json:"transition,omitempty"`
}

func (x *PropDocument) Reset() {
	*x = PropDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_propDocument_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropDocument) ProtoMessage() {}

func (x *PropDocument) ProtoReflect() protoreflect.Message {
	mi := &file_propDocument_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropDocument.ProtoReflect.Descriptor instead.
func (*PropDocument) Descriptor() ([]byte, []int) {
	return file_propDocument_proto_rawDescGZIP(), []int{0}
}

func (x *PropDocument) GetApplicationInfo() *ApplicationInfo {
	if x != nil {
		return x.ApplicationInfo
	}
	return nil
}

func (x *PropDocument) GetCues() []*Cue {
	if x != nil {
		return x.Cues
	}
	return nil
}

func (x *PropDocument) GetTransition() *Transition {
	if x != nil {
		return x.Transition
	}
	return nil
}

var File_propDocument_proto protoreflect.FileDescriptor

var file_propDocument_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x70, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x10, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x09, 0x63, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x65, 0x66, 0x66, 0x65,
	0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaa, 0x01, 0x0a, 0x0c, 0x50, 0x72,
	0x6f, 0x70, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x43, 0x0a, 0x10, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x41,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x20, 0x0a, 0x04, 0x63, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x75, 0x65, 0x52, 0x04, 0x63, 0x75, 0x65,
	0x73, 0x12, 0x33, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x1c, 0x5a, 0x1a, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_propDocument_proto_rawDescOnce sync.Once
	file_propDocument_proto_rawDescData = file_propDocument_proto_rawDesc
)

func file_propDocument_proto_rawDescGZIP() []byte {
	file_propDocument_proto_rawDescOnce.Do(func() {
		file_propDocument_proto_rawDescData = protoimpl.X.CompressGZIP(file_propDocument_proto_rawDescData)
	})
	return file_propDocument_proto_rawDescData
}

var file_propDocument_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_propDocument_proto_goTypes = []interface{}{
	(*PropDocument)(nil),    // 0: rv.data.PropDocument
	(*ApplicationInfo)(nil), // 1: rv.data.ApplicationInfo
	(*Cue)(nil),             // 2: rv.data.Cue
	(*Transition)(nil),      // 3: rv.data.Transition
}
var file_propDocument_proto_depIdxs = []int32{
	1, // 0: rv.data.PropDocument.application_info:type_name -> rv.data.ApplicationInfo
	2, // 1: rv.data.PropDocument.cues:type_name -> rv.data.Cue
	3, // 2: rv.data.PropDocument.transition:type_name -> rv.data.Transition
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_propDocument_proto_init() }
func file_propDocument_proto_init() {
	if File_propDocument_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	file_cue_proto_init()
	file_effects_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_propDocument_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_propDocument_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_propDocument_proto_goTypes,
		DependencyIndexes: file_propDocument_proto_depIdxs,
		MessageInfos:      file_propDocument_proto_msgTypes,
	}.Build()
	File_propDocument_proto = out.File
	file_propDocument_proto_rawDesc = nil
	file_propDocument_proto_goTypes = nil
	file_propDocument_proto_depIdxs = nil
}
