// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: proscreen.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProPresenterScreen_ScreenType int32

const (
	ProPresenterScreen_SCREEN_TYPE_UNKNOWN  ProPresenterScreen_ScreenType = 0
	ProPresenterScreen_SCREEN_TYPE_AUDIENCE ProPresenterScreen_ScreenType = 1
	ProPresenterScreen_SCREEN_TYPE_STAGE    ProPresenterScreen_ScreenType = 2
)

// Enum value maps for ProPresenterScreen_ScreenType.
var (
	ProPresenterScreen_ScreenType_name = map[int32]string{
		0: "SCREEN_TYPE_UNKNOWN",
		1: "SCREEN_TYPE_AUDIENCE",
		2: "SCREEN_TYPE_STAGE",
	}
	ProPresenterScreen_ScreenType_value = map[string]int32{
		"SCREEN_TYPE_UNKNOWN":  0,
		"SCREEN_TYPE_AUDIENCE": 1,
		"SCREEN_TYPE_STAGE":    2,
	}
)

func (x ProPresenterScreen_ScreenType) Enum() *ProPresenterScreen_ScreenType {
	p := new(ProPresenterScreen_ScreenType)
	*p = x
	return p
}

func (x ProPresenterScreen_ScreenType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProPresenterScreen_ScreenType) Descriptor() protoreflect.EnumDescriptor {
	return file_proscreen_proto_enumTypes[0].Descriptor()
}

func (ProPresenterScreen_ScreenType) Type() protoreflect.EnumType {
	return &file_proscreen_proto_enumTypes[0]
}

func (x ProPresenterScreen_ScreenType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProPresenterScreen_ScreenType.Descriptor instead.
func (ProPresenterScreen_ScreenType) EnumDescriptor() ([]byte, []int) {
	return file_proscreen_proto_rawDescGZIP(), []int{0, 0}
}

type ProPresenterScreen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                   string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ScreenType             ProPresenterScreen_ScreenType `protobuf:"varint,2,opt,name=screen_type,json=screenType,proto3,enum=rv.data.ProPresenterScreen_ScreenType" json:"screen_type,omitempty"`
	BackgroundColor        *Color                        `protobuf:"bytes,6,opt,name=background_color,json=backgroundColor,proto3" json:"background_color,omitempty"`
	Uuid                   *UUID                         `protobuf:"bytes,7,opt,name=uuid,proto3" json:"uuid,omitempty"`
	BackgroundColorEnabled bool                          `protobuf:"varint,8,opt,name=background_color_enabled,json=backgroundColorEnabled,proto3" json:"background_color_enabled,omitempty"`
	// Types that are assignable to Arrangement:
	//	*ProPresenterScreen_ArrangementSingle
	//	*ProPresenterScreen_ArrangementCombined
	//	*ProPresenterScreen_ArrangementEdgeBlend
	Arrangement isProPresenterScreen_Arrangement `protobuf_oneof:"Arrangement"`
}

func (x *ProPresenterScreen) Reset() {
	*x = ProPresenterScreen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proscreen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProPresenterScreen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProPresenterScreen) ProtoMessage() {}

func (x *ProPresenterScreen) ProtoReflect() protoreflect.Message {
	mi := &file_proscreen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProPresenterScreen.ProtoReflect.Descriptor instead.
func (*ProPresenterScreen) Descriptor() ([]byte, []int) {
	return file_proscreen_proto_rawDescGZIP(), []int{0}
}

func (x *ProPresenterScreen) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProPresenterScreen) GetScreenType() ProPresenterScreen_ScreenType {
	if x != nil {
		return x.ScreenType
	}
	return ProPresenterScreen_SCREEN_TYPE_UNKNOWN
}

func (x *ProPresenterScreen) GetBackgroundColor() *Color {
	if x != nil {
		return x.BackgroundColor
	}
	return nil
}

func (x *ProPresenterScreen) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *ProPresenterScreen) GetBackgroundColorEnabled() bool {
	if x != nil {
		return x.BackgroundColorEnabled
	}
	return false
}

func (m *ProPresenterScreen) GetArrangement() isProPresenterScreen_Arrangement {
	if m != nil {
		return m.Arrangement
	}
	return nil
}

func (x *ProPresenterScreen) GetArrangementSingle() *ProPresenterScreen_SingleArrangement {
	if x, ok := x.GetArrangement().(*ProPresenterScreen_ArrangementSingle); ok {
		return x.ArrangementSingle
	}
	return nil
}

func (x *ProPresenterScreen) GetArrangementCombined() *ProPresenterScreen_CombinedArrangement {
	if x, ok := x.GetArrangement().(*ProPresenterScreen_ArrangementCombined); ok {
		return x.ArrangementCombined
	}
	return nil
}

func (x *ProPresenterScreen) GetArrangementEdgeBlend() *ProPresenterScreen_EdgeBlendArrangement {
	if x, ok := x.GetArrangement().(*ProPresenterScreen_ArrangementEdgeBlend); ok {
		return x.ArrangementEdgeBlend
	}
	return nil
}

type isProPresenterScreen_Arrangement interface {
	isProPresenterScreen_Arrangement()
}

type ProPresenterScreen_ArrangementSingle struct {
	ArrangementSingle *ProPresenterScreen_SingleArrangement `protobuf:"bytes,3,opt,name=arrangement_single,json=arrangementSingle,proto3,oneof"`
}

type ProPresenterScreen_ArrangementCombined struct {
	ArrangementCombined *ProPresenterScreen_CombinedArrangement `protobuf:"bytes,4,opt,name=arrangement_combined,json=arrangementCombined,proto3,oneof"`
}

type ProPresenterScreen_ArrangementEdgeBlend struct {
	ArrangementEdgeBlend *ProPresenterScreen_EdgeBlendArrangement `protobuf:"bytes,5,opt,name=arrangement_edge_blend,json=arrangementEdgeBlend,proto3,oneof"`
}

func (*ProPresenterScreen_ArrangementSingle) isProPresenterScreen_Arrangement() {}

func (*ProPresenterScreen_ArrangementCombined) isProPresenterScreen_Arrangement() {}

func (*ProPresenterScreen_ArrangementEdgeBlend) isProPresenterScreen_Arrangement() {}

type ProPresenterScreen_SingleArrangement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Screens []*Screen `protobuf:"bytes,1,rep,name=screens,proto3" json:"screens,omitempty"`
}

func (x *ProPresenterScreen_SingleArrangement) Reset() {
	*x = ProPresenterScreen_SingleArrangement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proscreen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProPresenterScreen_SingleArrangement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProPresenterScreen_SingleArrangement) ProtoMessage() {}

func (x *ProPresenterScreen_SingleArrangement) ProtoReflect() protoreflect.Message {
	mi := &file_proscreen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProPresenterScreen_SingleArrangement.ProtoReflect.Descriptor instead.
func (*ProPresenterScreen_SingleArrangement) Descriptor() ([]byte, []int) {
	return file_proscreen_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ProPresenterScreen_SingleArrangement) GetScreens() []*Screen {
	if x != nil {
		return x.Screens
	}
	return nil
}

type ProPresenterScreen_CombinedArrangement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Screens []*Screen `protobuf:"bytes,1,rep,name=screens,proto3" json:"screens,omitempty"`
	Rows    uint32    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Columns uint32    `protobuf:"varint,3,opt,name=columns,proto3" json:"columns,omitempty"`
}

func (x *ProPresenterScreen_CombinedArrangement) Reset() {
	*x = ProPresenterScreen_CombinedArrangement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proscreen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProPresenterScreen_CombinedArrangement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProPresenterScreen_CombinedArrangement) ProtoMessage() {}

func (x *ProPresenterScreen_CombinedArrangement) ProtoReflect() protoreflect.Message {
	mi := &file_proscreen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProPresenterScreen_CombinedArrangement.ProtoReflect.Descriptor instead.
func (*ProPresenterScreen_CombinedArrangement) Descriptor() ([]byte, []int) {
	return file_proscreen_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ProPresenterScreen_CombinedArrangement) GetScreens() []*Screen {
	if x != nil {
		return x.Screens
	}
	return nil
}

func (x *ProPresenterScreen_CombinedArrangement) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ProPresenterScreen_CombinedArrangement) GetColumns() uint32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

type ProPresenterScreen_EdgeBlendArrangement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScreenCount uint32       `protobuf:"varint,1,opt,name=screen_count,json=screenCount,proto3" json:"screen_count,omitempty"`
	Screens     []*Screen    `protobuf:"bytes,2,rep,name=screens,proto3" json:"screens,omitempty"`
	EdgeBlends  []*EdgeBlend `protobuf:"bytes,3,rep,name=edge_blends,json=edgeBlends,proto3" json:"edge_blends,omitempty"`
}

func (x *ProPresenterScreen_EdgeBlendArrangement) Reset() {
	*x = ProPresenterScreen_EdgeBlendArrangement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proscreen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProPresenterScreen_EdgeBlendArrangement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProPresenterScreen_EdgeBlendArrangement) ProtoMessage() {}

func (x *ProPresenterScreen_EdgeBlendArrangement) ProtoReflect() protoreflect.Message {
	mi := &file_proscreen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProPresenterScreen_EdgeBlendArrangement.ProtoReflect.Descriptor instead.
func (*ProPresenterScreen_EdgeBlendArrangement) Descriptor() ([]byte, []int) {
	return file_proscreen_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ProPresenterScreen_EdgeBlendArrangement) GetScreenCount() uint32 {
	if x != nil {
		return x.ScreenCount
	}
	return 0
}

func (x *ProPresenterScreen_EdgeBlendArrangement) GetScreens() []*Screen {
	if x != nil {
		return x.Screens
	}
	return nil
}

func (x *ProPresenterScreen_EdgeBlendArrangement) GetEdgeBlends() []*EdgeBlend {
	if x != nil {
		return x.EdgeBlends
	}
	return nil
}

var File_proscreen_proto protoreflect.FileDescriptor

var file_proscreen_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x0d, 0x73, 0x63, 0x72, 0x65,
	0x65, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x62, 0x61, 0x73, 0x69, 0x63,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xec, 0x07, 0x0a, 0x12,
	0x50, 0x72, 0x6f, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x63, 0x72, 0x65,
	0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x47, 0x0a, 0x0b, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x72, 0x76,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x72, 0x6f, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x2e, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0a, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x39, 0x0a, 0x10, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x76, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x0f, 0x62, 0x61, 0x63, 0x6b, 0x67,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x38, 0x0a,
	0x18, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x16, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x5e, 0x0a, 0x12, 0x61, 0x72, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x72,
	0x6f, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x41, 0x72, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x48, 0x00, 0x52, 0x11, 0x61, 0x72, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x64, 0x0a, 0x14, 0x61, 0x72, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x50, 0x72, 0x6f, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x63, 0x72, 0x65,
	0x65, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x64, 0x41, 0x72, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x13, 0x61, 0x72, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x68, 0x0a,
	0x16, 0x61, 0x72, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x64, 0x67,
	0x65, 0x5f, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e,
	0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x72, 0x6f, 0x50, 0x72, 0x65, 0x73, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x42,
	0x6c, 0x65, 0x6e, 0x64, 0x41, 0x72, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48,
	0x00, 0x52, 0x14, 0x61, 0x72, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x64,
	0x67, 0x65, 0x42, 0x6c, 0x65, 0x6e, 0x64, 0x1a, 0x3e, 0x0a, 0x11, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x41, 0x72, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x07,
	0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x52, 0x07,
	0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x1a, 0x6e, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x62, 0x69,
	0x6e, 0x65, 0x64, 0x41, 0x72, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x29,
	0x0a, 0x07, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x52, 0x07, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x1a, 0x99, 0x01, 0x0a, 0x14, 0x45, 0x64, 0x67, 0x65,
	0x42, 0x6c, 0x65, 0x6e, 0x64, 0x41, 0x72, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x07, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53,
	0x63, 0x72, 0x65, 0x65, 0x6e, 0x52, 0x07, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x12, 0x33,
	0x0a, 0x0b, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x64,
	0x67, 0x65, 0x42, 0x6c, 0x65, 0x6e, 0x64, 0x52, 0x0a, 0x65, 0x64, 0x67, 0x65, 0x42, 0x6c, 0x65,
	0x6e, 0x64, 0x73, 0x22, 0x56, 0x0a, 0x0a, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x43, 0x52, 0x45, 0x45, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x43,
	0x52, 0x45, 0x45, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x55, 0x44, 0x49, 0x45, 0x4e,
	0x43, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x43, 0x52, 0x45, 0x45, 0x4e, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x47, 0x45, 0x10, 0x02, 0x42, 0x0d, 0x0a, 0x0b, 0x41,
	0x72, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x1c, 0x5a, 0x1a, 0x63, 0x6f,
	0x6e, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proscreen_proto_rawDescOnce sync.Once
	file_proscreen_proto_rawDescData = file_proscreen_proto_rawDesc
)

func file_proscreen_proto_rawDescGZIP() []byte {
	file_proscreen_proto_rawDescOnce.Do(func() {
		file_proscreen_proto_rawDescData = protoimpl.X.CompressGZIP(file_proscreen_proto_rawDescData)
	})
	return file_proscreen_proto_rawDescData
}

var file_proscreen_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proscreen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proscreen_proto_goTypes = []interface{}{
	(ProPresenterScreen_ScreenType)(0),              // 0: rv.data.ProPresenterScreen.ScreenType
	(*ProPresenterScreen)(nil),                      // 1: rv.data.ProPresenterScreen
	(*ProPresenterScreen_SingleArrangement)(nil),    // 2: rv.data.ProPresenterScreen.SingleArrangement
	(*ProPresenterScreen_CombinedArrangement)(nil),  // 3: rv.data.ProPresenterScreen.CombinedArrangement
	(*ProPresenterScreen_EdgeBlendArrangement)(nil), // 4: rv.data.ProPresenterScreen.EdgeBlendArrangement
	(*Color)(nil),     // 5: rv.data.Color
	(*UUID)(nil),      // 6: rv.data.UUID
	(*Screen)(nil),    // 7: rv.data.Screen
	(*EdgeBlend)(nil), // 8: rv.data.EdgeBlend
}
var file_proscreen_proto_depIdxs = []int32{
	0,  // 0: rv.data.ProPresenterScreen.screen_type:type_name -> rv.data.ProPresenterScreen.ScreenType
	5,  // 1: rv.data.ProPresenterScreen.background_color:type_name -> rv.data.Color
	6,  // 2: rv.data.ProPresenterScreen.uuid:type_name -> rv.data.UUID
	2,  // 3: rv.data.ProPresenterScreen.arrangement_single:type_name -> rv.data.ProPresenterScreen.SingleArrangement
	3,  // 4: rv.data.ProPresenterScreen.arrangement_combined:type_name -> rv.data.ProPresenterScreen.CombinedArrangement
	4,  // 5: rv.data.ProPresenterScreen.arrangement_edge_blend:type_name -> rv.data.ProPresenterScreen.EdgeBlendArrangement
	7,  // 6: rv.data.ProPresenterScreen.SingleArrangement.screens:type_name -> rv.data.Screen
	7,  // 7: rv.data.ProPresenterScreen.CombinedArrangement.screens:type_name -> rv.data.Screen
	7,  // 8: rv.data.ProPresenterScreen.EdgeBlendArrangement.screens:type_name -> rv.data.Screen
	8,  // 9: rv.data.ProPresenterScreen.EdgeBlendArrangement.edge_blends:type_name -> rv.data.EdgeBlend
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proscreen_proto_init() }
func file_proscreen_proto_init() {
	if File_proscreen_proto != nil {
		return
	}
	file_screens_proto_init()
	file_basicTypes_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proscreen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProPresenterScreen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proscreen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProPresenterScreen_SingleArrangement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proscreen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProPresenterScreen_CombinedArrangement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proscreen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProPresenterScreen_EdgeBlendArrangement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proscreen_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ProPresenterScreen_ArrangementSingle)(nil),
		(*ProPresenterScreen_ArrangementCombined)(nil),
		(*ProPresenterScreen_ArrangementEdgeBlend)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proscreen_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proscreen_proto_goTypes,
		DependencyIndexes: file_proscreen_proto_depIdxs,
		EnumInfos:         file_proscreen_proto_enumTypes,
		MessageInfos:      file_proscreen_proto_msgTypes,
	}.Build()
	File_proscreen_proto = out.File
	file_proscreen_proto_rawDesc = nil
	file_proscreen_proto_goTypes = nil
	file_proscreen_proto_depIdxs = nil
}
