// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: stage.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Stage) Reset() {
	*x = Stage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_stage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_stage_proto_rawDescGZIP(), []int{0}
}

type Stage_Layout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid  *UUID  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slide *Slide `protobuf:"bytes,3,opt,name=slide,proto3" json:"slide,omitempty"`
}

func (x *Stage_Layout) Reset() {
	*x = Stage_Layout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stage_Layout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage_Layout) ProtoMessage() {}

func (x *Stage_Layout) ProtoReflect() protoreflect.Message {
	mi := &file_stage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage_Layout.ProtoReflect.Descriptor instead.
func (*Stage_Layout) Descriptor() ([]byte, []int) {
	return file_stage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Stage_Layout) GetUuid() *UUID {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Stage_Layout) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stage_Layout) GetSlide() *Slide {
	if x != nil {
		return x.Slide
	}
	return nil
}

type Stage_Document struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationInfo *ApplicationInfo `protobuf:"bytes,1,opt,name=application_info,json=applicationInfo,proto3" json:"application_info,omitempty"`
	Layouts         []*Stage_Layout  `protobuf:"bytes,2,rep,name=layouts,proto3" json:"layouts,omitempty"`
}

func (x *Stage_Document) Reset() {
	*x = Stage_Document{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stage_Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage_Document) ProtoMessage() {}

func (x *Stage_Document) ProtoReflect() protoreflect.Message {
	mi := &file_stage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage_Document.ProtoReflect.Descriptor instead.
func (*Stage_Document) Descriptor() ([]byte, []int) {
	return file_stage_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Stage_Document) GetApplicationInfo() *ApplicationInfo {
	if x != nil {
		return x.ApplicationInfo
	}
	return nil
}

func (x *Stage_Document) GetLayouts() []*Stage_Layout {
	if x != nil {
		return x.Layouts
	}
	return nil
}

type Stage_ScreenAssignment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Screen *CollectionElementType `protobuf:"bytes,1,opt,name=screen,proto3" json:"screen,omitempty"`
	Layout *CollectionElementType `protobuf:"bytes,2,opt,name=layout,proto3" json:"layout,omitempty"`
}

func (x *Stage_ScreenAssignment) Reset() {
	*x = Stage_ScreenAssignment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stage_ScreenAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage_ScreenAssignment) ProtoMessage() {}

func (x *Stage_ScreenAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_stage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage_ScreenAssignment.ProtoReflect.Descriptor instead.
func (*Stage_ScreenAssignment) Descriptor() ([]byte, []int) {
	return file_stage_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Stage_ScreenAssignment) GetScreen() *CollectionElementType {
	if x != nil {
		return x.Screen
	}
	return nil
}

func (x *Stage_ScreenAssignment) GetLayout() *CollectionElementType {
	if x != nil {
		return x.Layout
	}
	return nil
}

var File_stage_proto protoreflect.FileDescriptor

var file_stage_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72,
	0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x10, 0x62, 0x61, 0x73, 0x69, 0x63, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf6, 0x02, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65, 0x1a,
	0x65, 0x0a, 0x06, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x24, 0x0a, 0x05, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x52,
	0x05, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x1a, 0x80, 0x01, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x43, 0x0a, 0x10, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2f, 0x0a, 0x07, 0x6c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x76, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x52, 0x07, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x73, 0x1a, 0x82, 0x01, 0x0a, 0x10, 0x53, 0x63,
	0x72, 0x65, 0x65, 0x6e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x36,
	0x0a, 0x06, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06,
	0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x36, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x72, 0x76, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x42, 0x1c,
	0x5a, 0x1a, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x65, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stage_proto_rawDescOnce sync.Once
	file_stage_proto_rawDescData = file_stage_proto_rawDesc
)

func file_stage_proto_rawDescGZIP() []byte {
	file_stage_proto_rawDescOnce.Do(func() {
		file_stage_proto_rawDescData = protoimpl.X.CompressGZIP(file_stage_proto_rawDescData)
	})
	return file_stage_proto_rawDescData
}

var file_stage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stage_proto_goTypes = []interface{}{
	(*Stage)(nil),                  // 0: rv.data.Stage
	(*Stage_Layout)(nil),           // 1: rv.data.Stage.Layout
	(*Stage_Document)(nil),         // 2: rv.data.Stage.Document
	(*Stage_ScreenAssignment)(nil), // 3: rv.data.Stage.ScreenAssignment
	(*UUID)(nil),                   // 4: rv.data.UUID
	(*Slide)(nil),                  // 5: rv.data.Slide
	(*ApplicationInfo)(nil),        // 6: rv.data.ApplicationInfo
	(*CollectionElementType)(nil),  // 7: rv.data.CollectionElementType
}
var file_stage_proto_depIdxs = []int32{
	4, // 0: rv.data.Stage.Layout.uuid:type_name -> rv.data.UUID
	5, // 1: rv.data.Stage.Layout.slide:type_name -> rv.data.Slide
	6, // 2: rv.data.Stage.Document.application_info:type_name -> rv.data.ApplicationInfo
	1, // 3: rv.data.Stage.Document.layouts:type_name -> rv.data.Stage.Layout
	7, // 4: rv.data.Stage.ScreenAssignment.screen:type_name -> rv.data.CollectionElementType
	7, // 5: rv.data.Stage.ScreenAssignment.layout:type_name -> rv.data.CollectionElementType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_stage_proto_init() }
func file_stage_proto_init() {
	if File_stage_proto != nil {
		return
	}
	file_basicTypes_proto_init()
	file_slide_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_stage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stage_Layout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stage_Document); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stage_ScreenAssignment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stage_proto_goTypes,
		DependencyIndexes: file_stage_proto_depIdxs,
		MessageInfos:      file_stage_proto_msgTypes,
	}.Build()
	File_stage_proto = out.File
	file_stage_proto_rawDesc = nil
	file_stage_proto_goTypes = nil
	file_stage_proto_depIdxs = nil
}
